### ISSUE TITLE
Advertising Management

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#11]
Is it possible to specify the client ID when displaying advertisements in posts?

**Comment by geekwright** [comment]
No. It just calls the system banner call. The client is determined there.

**Comment by aerograf** [comment]
I see. Thanks!

**Comment by aerograf** [comment]
How can I make that on one forum one advertising client, another another advertising client, etc. ?

**Comment by aerograf** [comment]
Moved to another branch
