### ISSUE TITLE
Can not see digest

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#14]
You can not see the digest in the administrative part. On the user part, the post is designated as a digest. In this case, the database digest is empty, and the mark is only in the topics table.

**Comment by aerograf** [comment]
No, the record does not occur in the database :(

**Comment by aerograf** [comment]
Hope for geekwright.
But the function itself, in the form as it was conceived, it seems to me, never worked.

**Comment by geekwright** [comment]
I have gone over the digest code, trying to figure out exactly how it is supposed to work, and have tried to make sure it really is doing that.

When you 'digest' a topic, it only sets the topic_digest column to '1'.  The digest table is not involved at all.

There is a separate process that populates the digest table. That process is the modules/newbb/digest.php script. The email_digest preference setting influences this, and can disable it entirely. If a digest has been generated more recently than the email_digest setting (weekly or daily) nothing happens.

If the digest is generated, it consists of the title and first few opening words from each topic marked for digest that have not already been included in a previous digest. Only the opening topic post is included -- no replies.

Nothing in the newbb module ever invokes the digest.php script. It can be invoked in a browser window, but it appears that it was intended to be used in a cron job.

The digest process is supposed to send the digest as pm/email, but that hasn't worked for me yet. I'll have to look a little deeper.

The digest.php script does not require any authentication or token to operate, so it could potentially be used in malicious activities.

While the feature provides a curated "What's new" feature, I suspect that the fully automatic rss feed is used more often.

There are still several issues with the digest feature. We should probably make a decision to either commit to cleaning it up and fixing it, complete with better controls, UI and documentation, OR just remove it. Leaving it as is not a good option.

Any thoughts?

**Comment by aerograf** [comment]
I have an offer.
If you remove the generation of digest at all, and when you mark in the subject that this digest is written to the digest table, and already by the decision of the administrator, the mailing is done.
Or even remove this function, and extend the notification to subscribe to new messages. Although this function already exists. Leave just the opportunity to mark a topic as digest. But without the possibility of administration.
How such an option?

**Comment by geekwright** [comment]
This last change (#22) puts a button on the digest page to create the digest and mail it to the subscribers. Let me know what you think.

**Comment by aerograf** [comment]
This is the best solution.
Question about sending messages. Is it distributed to anyone in the XOOPS database?

**Comment by geekwright** [comment]
It is driven by the notification system. Anyone who subscribes to the "digest" notification gets it by PM or email, their preference.
![image](https://user-images.githubusercontent.com/3181636/30393209-fc2ae6aa-9884-11e7-9d76-d5c548ac2c0c.png)

**Comment by aerograf** [comment]
Many thanks!
I will test, etc.
While this branch is closed?

**Comment by aerograf** [comment]
Podneu again discussion.
Messages are not sent to the mail. (I could not get).
As it seems to me, it is necessary to change the digest settings on both on and off instead of daily and weekly.
Your opinion?

**Comment by aerograf** [comment]
Mail has earned.
