### ISSUE TITLE
Creating PDF

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#19]
The question is about finding the icon in the template ...

**Comment by geekwright** [comment]
It is set in class/post.php line 627, and referenced in the templates trough $topic_post.thread_action in newbb_thread.tpl

**Comment by aerograf** [comment]
Yes, it is. But for some reason, the icon is not shown when activated.
He says in his permission that it is possible to create pdf, but there are no icons.
The placement tcpdf.php indicated (/class/libraries/vendor/tecnickcom/tcpdf/tcpdf.php), etc. but does not work. If I prescribe directly in the template, everything is OK, but here everything is called through functions, so I ask.

**Comment by aerograf** [comment]
Ok
