### ISSUE TITLE
Question on "Topic types"

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#20]
How should this function work?
How did not try to change something - it does not work.

**Comment by aerograf** [comment]
I'm trying to figure out how it should work.
If I understand correctly, then the templates are created in the table newbb_type and newbb_type_forum, and then it is possible to apply them to the forum, for this there is an entry in newbb_topics.
But nothing happens.
What is the purpose of this function?
Sorry for the stupid question ...

**Comment by mambax7** [comment]
which function are you talking about ? In which file?

**Comment by aerograf** [comment]
This applies to admin_type_manager.php

**Comment by aerograf** [comment]
How it should work understood.
Now we need to force it to work :)

**Comment by aerograf** [comment]
Ок
