### ISSUE TITLE
Question: clearing cache after creating category

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#3]
After creating the category and new forums, you need to clear the xoops cache. So it is conceived or is it a bug?

**Comment by geekwright** [comment]
I'd say bug :smile: 

Since there are newbb cache keys that include group list hashes, there is no simple list of keys that we need to clear.

The newbb cache code is all going through XMF. The XMF the Cache helper in 2.6 has a clear() method that would be perfect, but that depends on the hierarchical keys of the underlying cache. We will have to work around it for 2.5

There are radical changes to cache in 2.6, so keeping any cache specific logic separate will help us long term.

Probably the cleanest way to add this would be a static NewbbUtility::cleanCache() method that you can call when needed. That would look something like this:


```php
static function cleanCache()
{
    $cacheHelper = new \Xmf\Module\Helper\Cache('newbb');
    if (method_exists($directory,'clear')) {
        $cacheHelper->clear();
        return;
    }
    // for 2.5 systems, clear everything
    require_once XOOPS_ROOT_PATH . '/modules/system/class/maintenance.php';
    $maintenance = new SystemMaintenance();
    $cacheList = array(
        3, // xoops_cache
    );
    $maintenance->CleanCache($cacheList);
}
```

That should work in both cases, even if it is a bit inefficient right now.

**Comment by aerograf** [comment]
**geekwright** 
Thanks for the answer!
Now who will make the change? :)

**Comment by aerograf** [comment]
**geekwright**
Another question.
There is a problem when moderating posts. And with the approval of posts. If you do not select anything, the error pops up. In the rest of it works. Your view is needed.

**Comment by geekwright** [comment]
> Now who will make the change? :)

If you would like to make the changes, feel free. This module really deserves a new champion to advance it. It is important enough to XOOPS that I'm very willing to make time to work on it if needed. But, I get a lot of distractions and I don't want to stand in the way of progress. 

I would be happy with just consulting as needed, but if you would prefer I did this change, just tell me.

**Comment by aerograf** [comment]
Yes, we will do everything.
The question remained below. With him I could not figure out :(
> There is a problem when moderating posts. And with the approval of posts. If you do not select anything, the error pops up. In the rest of it works. Your view is needed.

**Comment by geekwright** [comment]
I think #6 solves the error. Please verify.

Checks on post_id expected it to be an array, but the default value was an integer 0 instead of an empty array. Oops!

**Comment by aerograf** [comment]
Thank you!!!
Everything worked. Corrected the message in action.topic.php
And if I'm not too intrusive then another question.
Just now I noticed that XoopsFormDhtmlTextArea does not display buttons ... Have not you seen this?

**Comment by geekwright** [comment]
I can not replicate the issue with the buttons. It works here, so I'm not sure what is going on.

It looks like font-awesome is missing. Does the browser console show any messages?

**Comment by aerograf** [comment]
Most likely the problem is with me. I will sort this out. There are no other problems with this module.
Thanks for the help. We will prepare the module further.

**Comment by aerograf** [comment]
Seems to have found the reason.
It's worth mentioning $cacheHelper = NewbbUtility::cleanCache (); and everything returns to the place ...

**Comment by aerograf** [comment]
The problem is when $ cacheList 3, cleaning the cache of xoops. If you specify another (1 or 2) then the buttons appear. But the list does not update. . .

**Comment by geekwright** [comment]
You can assign it as `$cacheList = [1, 2, 3];` if that helps.

There are three separate caches you can specify:
1 - smarty_cache - cached smarty output
2 - smarty_compile - compiled templates
3 - xoops_cache - all XoopsCache contents (includes the Xmf cache helper)

**Comment by aerograf** [comment]
I also tried this option. Does not help.
Perhaps the problem in installing xoops is with me.
I'll try to figure it out.
Thanks for the help!

**Comment by aerograf** [comment]
One more question.
How best to do redirection to functions.welcome.inc.php on the automatically created forum, when the user first logs on?

**Comment by aerograf** [comment]
> Just now I noticed that XoopsFormDhtmlTextArea does not display buttons ... 
Found a solution:
```
static function cleanCache()
{
    $cacheHelper = new \Xmf\Module\Helper\Cache('newbb');
    if (method_exists($cacheHelper,'clear')) {
        $cacheHelper->clear();
        return;
    }
    // for 2.5 systems, clear everything
    require_once XOOPS_ROOT_PATH . '/modules/system/class/maintenance.php';
    $maintenance = new SystemMaintenance();
    $cacheList = array(
        3, // xoops_cache
    );
    $maintenance->CleanCache($cacheList);
    xoops_setActiveModules();
}
```

**Comment by aerograf** [comment]
Остался этот вопрос:
> One more question.
> How best to do redirection to functions.welcome.inc.php on the automatically created forum, when the user first logs on?

**Comment by aerograf** [comment]
Is it possible to specify the client ID when displaying advertisements in posts?

**Comment by aerograf** [comment]
No reports are displayed

**Comment by aerograf** [comment]
Error creating Digest
**Error - Please go back and try again.
sql:UPDATE host__bb_topics SET topic_digest = 1, digest_time = 1505075890 WHERE topic_id = 2**

Error creating Sticky
**Error - Please go back and try again.
sql:UPDATE host__bb_topics SET topic_sticky=1 WHERE topic_id = 2**


Error creating Lock
**Error - Please go back and try again.
sql:UPDATE host__bb_topics SET topic_status = 1 WHERE topic_id = 2**

**Comment by mambax7** [comment]
For new issues, please open new incident, so once we fix it, we can close it :)
