### ISSUE TITLE
Help text

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#35]
The problem with all XOOPS modules is the minimum information about the functionality of the module and how to configure it. Many functions are simply not used due to a lack of understanding of its operation. I showed this module because I had to spend a lot of time to understand how the function should work. And a user who does not get into the code does not understand what to do at all.
I have a question, and at the same time an offer.
There are help files. They are needed. But you need to add a tooltip. Or insert an explanatory text, if possible, into all the tabs.
Your opinion?
Sorry for English ....

**Comment by aerograf** [comment]
I'm ready to do the work on this module, but then I'll need help in correcting the language files.
And if you do this, you need to create a separate file with help text. How best to connect it, call it, etc. ?
Also for the user side.
I think this will be a big step towards the users.

**Comment by aerograf** [comment]
Cooking and making help for each tab?
Or do you think this is redundant?

**Comment by geekwright** [comment]
Some tabs are fairly easy to grasp, but some make little sense without a detailed explanation -- like digests :smile: 

I have no objections to a help page for each tab if you think it is the best way to present it.

**Comment by aerograf** [comment]
I suggest this option:
https://github.com/mambax7/newbb5/pull/43

**Comment by aerograf** [comment]
Done
