### ISSUE TITLE
Set default permissions

### ISSUE THREAD

**Issue by mambax7** [mambax7/newbb5#37]
It seems like I can't save the default permissions. Can somebody test and confirm it? 
Steps: 
![image](https://user-images.githubusercontent.com/613686/30475169-e3a56920-99d3-11e7-8e69-c104031f4b34.png)

**Comment by aerograf** [comment]
Yes. I have the same.

**Comment by geekwright** [comment]
The default permissions are stored in the cache -- which seems to be aggressively cleared now.

Probably was never a great place to keep it. But, we also seem to have gone overboard on the cache clearing. We really should only be doing the full clearing when the actual permissions are updated.

There are really 2 problems here.

**Comment by aerograf** [comment]
Is it possible to save to a file txt, bd?
Cuzoshko Cache will be cleaned constantly ...
In the database, this is not necessary.

**Comment by mambax7** [comment]
Richard, are you going to look into it?

**Comment by geekwright** [comment]
We still need to look at the excessive cache clearing, but #53 makes the permission templates persistent.

**Comment by aerograf** [comment]
Thank you. Working. But I'll check it out.

**Comment by aerograf** [comment]
The given problem like as is solved. Can be closed, or will you change?

**Comment by mambax7** [comment]
Actually, Richard should be the one deciding on this....

**Comment by geekwright** [comment]
If areograf is happy, I satisfied with closing this one.

I'll be reviewing the issues with the cache clearing separately.

**Comment by aerograf** [comment]
geekwright Thanks for your work!
