### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#40]
Error while updating:
Error: Error: Call to undefined method NewbbUtility :: userIsAdmin () in the file /modules/newbb/include/common.php line 57

**Comment by aerograf** [comment]
An error with this.
$ publisherIsAdmin = NewbbUtility :: userIsAdmin ();

**Comment by aerograf** [comment]
userIsAdmin in utilities is not present ....

**Comment by aerograf** [comment]
You must rename class/Helper.php to class/helper.php

**Comment by mambax7** [comment]
Done
