### ISSUE TITLE
User permission table

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#42]
How do you look at what would make the table of user permissions not text, but icons?

**Comment by mambax7** [comment]
What do you mean? I am not sure, I understand...

**Comment by aerograf** [comment]
![tableuser](https://user-images.githubusercontent.com/25700040/30514280-53f74c60-9b1a-11e7-86fe-c104244f8f77.png)

**Comment by aerograf** [comment]
Can be placed in a row. A 'title' leave the existing text

**Comment by aerograf** [comment]
It looks like this. But you can and girlfriend.
Your opinion?
![perm](https://user-images.githubusercontent.com/25700040/30541875-c80d3774-9c85-11e7-9e62-f2fb6547c5e5.png)

**Comment by aerograf** [comment]
If I do, I will use other icons.

**Comment by aerograf** [comment]
That's how it looks.
http://xoops.shmel.org/forums/viewforum.php?forum=1
![perm1](https://user-images.githubusercontent.com/25700040/30545884-a0b4d39a-9c93-11e7-9db9-2b09fdfed7ee.png)

**Comment by mambax7** [comment]
That looks good!  Richard, what do you think?

**Comment by aerograf** [comment]
https://github.com/mambax7/newbb5/pull/46

**Comment by geekwright** [comment]
> ... what do you think?

Actually, it looks like a nightmare in some situations :(

It would take a *long* time to be able to remember the meaning of each of those icons. Any time the user  needed to figure it out would end up being a negative experience while they hover over each icon trying to find what it means.

Just as bad, the tooltips won't work right on mobile -- you can make up for the missing hover events with javascript, but the icons are too small and close together (smaller than a finger tip.)

Why not one single prompt for permissions, and clicking brings up the full text list in a modal dialog?

That would be a cleaner interface for both desktop and mobile. That would take up much less screen space, and the information would be easier to access and read in the somewhat rare case when you need to check it.

Most of this should probably be a theme feature, but we should reflect the market trends for our default templates. Device type varies a lot by region, but the global access statistics show mobile devices  are the largest part of web traffic.

**Comment by aerograf** [comment]
Ie modal window as an option will do?

**Comment by aerograf** [comment]
On mobile devices did not really think.
I will look for another solution.
Until I close the branch.
