### ISSUE TITLE
Error block

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#50]
When switching from the "Recent Posts" block, the "Posts" link gives an error:
`Error: Error: Call to a member function prefix () on null in /modules/newbb/class/online.php line 327`

**Comment by geekwright** [comment]
Looks like there could be paths through the code that would not call $onlineHandler->init(). That would leave the $db property unset.

The handler instantiation always gets passes a XoopsDatabase instance, so a switch to using it should fix it.

Please test fully, as I have not reproduced the error locally, but I can see that it might in some cases.

**Comment by aerograf** [comment]
Thank you.
The problem is resolved.
I test further.
