### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#54]
The warning that appears on the page with the NEWBB block posted on it:
`array_merge (): Argument # 1 is not an array in the file /modules/newbb/include/functions.config.php line 41`

**Comment by geekwright** [comment]
It seems to only occur when there isn't an active module - like on the front page.

Looking at code, blocks should never rely on a global $xoopsModuleConfig, so any newbb blocks using the newbbLoadConfig() function in include/functions.config.php will fail this way.

I am a bit confused by why this code is merging the configs this way. If newbb is the active module, xoopsModuleConfig would already be set with the newbb configs. If newbb isn't the active module, why merge them into some other module's configs. Seems that could create some hard to diagnose bugs :frowning_face: 

Need to think about this ...

**Comment by aerograf** [comment]
I put the module in the work, that would reveal the smaller problems.
https://www.shmel.org/forums/
I think this will help.

**Comment by mambax7** [comment]
Fixed in: https://github.com/mambax7/newbb5/commit/71d63aa5847a3f8daea81e4b625318fa5dca804a

**Comment by aerograf** [comment]
Checked. Working.
Thank you!
