### ISSUE TITLE
What is the Content of the .htaccess File

### ISSUE THREAD

**Issue by AlexL777** [mambax7/newbb5#55]
Hello Developers,

finally a module that is compatible with xoops 2.5.9, but unfortunately it does not work if SEO URLs are activated.

Where do I get the contents of the .htaccess file.

Can you help me in that sense?

Thanks in advance and thanks also for the module.

**Comment by mambax7** [comment]
.htaccess file is in the main directory. 
Thank you for testing, and please let us know about any problems...

**Comment by AlexL777** [comment]
Hi @mambax7 

With this .htaccess the SEF URLs unfortunately do not work.

```
RewriteEngine on
RewriteBase /modules/newbb/
RewriteRule ^([a-z]+)-([0-9]+)(/(.+))? modules/newbb/seo.php?seoOp=$1&seoArg=$2&seoOther=$4&%{QUERY_STRING} [L]
#RewriteRule ^(.*)$ $1 [L]
```

How did you get it in the test environment?

I have just activated the SEO URLs, added in the .htaccess RewriteBase `/modules/newbb`. But this does not affect the front end under `/modules/newbb`.

What am I doing wrong?

Thanks in Advance.

**Comment by ihackcode** [comment]
One of these should work.
`#.htaccess located in XOOPS_PATH. For SEO-URL (option A)
#RewriteRule ^modules/newbb/([a-z]+)-([0-9]+)(/(.+))? modules/newbb/seo.php?seoOp=$1&seoArg=$2&seoOther=$4&%{QUERY_STRING} [L]

#.htaccess located in modules/newbb. For SEO-URL (option B)
#RewriteRule ^([a-z]+)-([0-9]+)(/(.+))? seo.php?seoOp=$1&seoArg=$2&seoOther=$4&%{QUERY_STRING} [L]`
