### ISSUE TITLE
Forum Description

### ISSUE THREAD

**Issue by aerograf** [mambax7/newbb5#58]
Is it possible to make it possible to make own rules for each forum? Not a description that already has a rule or area for text.

**Comment by mambax7** [comment]
Give an example of what you're looking for ...

**Comment by aerograf** [comment]
Something like this ...
![rules](https://user-images.githubusercontent.com/25700040/32991621-e5d39b22-cd4f-11e7-8306-69af421ea744.png)

**Comment by mambax7** [comment]
Sorry, but I am still not quite sure what you mean? What should be there inside this box?

**Comment by aerograf** [comment]
When creating the forum, it is possible to make a description of the forum, which will be visible in the list of forums, but if you go to it, where the forum topics, the description is no longer there ...

**Comment by mambax7** [comment]
OK, I see now...

**Comment by mambax7** [comment]
Check it out: https://github.com/mambax7/newbb5/commit/ebdc4f7201d079f7557df898a4322b7299b8a67e

**Comment by aerograf** [comment]
Thank you. I think this mod will be useful :-)

**Comment by aerograf** [comment]
And BB codes are not converted?

**Comment by mambax7** [comment]
Try now with the latest update

**Comment by aerograf** [comment]
And how is my option?
https://github.com/mambax7/newbb5/compare/master...aerograf:patch-1

**Comment by aerograf** [comment]
If you use the variant proposed by you:
`$ this-> initVar ('forum_desc', XOBJ_DTYPE_TXTAREA);`
It turns out like this:
![rules1](https://user-images.githubusercontent.com/25700040/33004872-28bd0cfa-cdd4-11e7-8a35-dbac802d8023.png)
With my version it turns out better. But a little more work.

**Comment by mambax7** [comment]
I guess, you have to have one or the other. 
Just updated it....

**Comment by aerograf** [comment]
Tried it differently. My option works. At least I have.
