### ISSUE TITLE
After Fresh Installation no Button Labels and no Icons

### ISSUE THREAD

**Issue by AlexL777** [mambax7/newbb5#67]
Hi Developers,

I just installed NewBB on freshly installed Xoops portal. Unfortunately, no icons and buttons are displayed in the frontend.

I have the last branch from here from Github. Here below a screenshot.

![xoops-newbb-forum-error](https://user-images.githubusercontent.com/7885632/33806420-43074252-ddc8-11e7-826f-a85d6a84a45d.jpg)

How can I solve the problem?

Thanks in advance.

**Comment by mambax7** [comment]
1) Copy the .tpl files from the folder: 
\modules\newbb\EXTRA\themes\xbootstrap\modules\newbb
to:
\themes\xbootstrap\modules\newbb

2) Go to Admin Maintenance (/modules/system/admin.php?fct=maintenance) and clean cache folders

That should fix the issue for you

Thank you for testing...
